# top-level makefile for building uart character para-virtualized driver
#
# author: amit vasudevan (amitvasudevan@acm.org)

# this makefile depends on two external environment variable definitions
#
# PATH_UXMHF = full path to uxmhf (git) source tree
# PATH_RPI_LINUX_44y = full path to raspberry pi3 linux (git) source tree (branch 4.4.y)
# PATH_CROSS_COMPILE_TOOLS = full path to raspberry pi3 cross compile toolchain (git) source tree
#


.PHONY: all
all: 
	@echo $(PATH_UXMHF)
	@echo $(PATH_RPI_LINUX_44y)
	@echo $(PATH_CROSS_COMPILE_TOOLS)
	make -f Makefile.kmod -C $$PATH_RPI_LINUX_44y ARCH=arm CROSS_COMPILE=$$PATH_CROSS_COMPILE_TOOLS/arm-linux-gnueabihf- M=$$PWD
